package UD04_03Tenis.entity;
// Generated 26 ene 2025 16:50:50 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Players generated by hbm2java
 */
@Entity
@Table(name = "players", catalog = "NBA")
public class Players implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "code", unique = true, nullable = false)
	private int code;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Team_name")
	private Teams teams;
	@Column(name = "Name", length = 30)
	private String name;
	@Column(name = "Origin", length = 20)
	private String origin;
	@Column(name = "Height", length = 4)
	private String height;
	@Column(name = "Weight")
	private Integer weight;
	@Column(name = "Position", length = 5)
	private String position;
	@Column(name = "Salary")
	private Integer salary;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "players")
	private Set<Stats> stats = new HashSet<Stats>(0);

	public Players() {}

	public Players(int code) {
		this.code = code;}

	public Players(int code, Teams teams, String name, String origin, 
			String height, Integer weight, String position,
			Integer salary, Set<Stats> stats) {
		this.code = code;
		this.teams = teams;
		this.name = name;
		this.origin = origin;
		this.height = height;
		this.weight = weight;
		this.position = position;
		this.salary = salary;
		this.stats = stats;}

	public int getCode() {
		return this.code;}

	public void setCode(int code) {
		this.code = code;}

	public Teams getTeams() {
		return this.teams;}

	public void setTeams(Teams teams) {
		this.teams = teams;}

	public String getName() {
		return this.name;}

	public void setName(String name) {
		this.name = name;}

	public String getOrigin() {
		return this.origin;}

	public void setOrigin(String origin) {
		this.origin = origin;}

	public String getHeight() {
		return this.height;}

	public void setHeight(String height) {
		this.height = height;}

	public Integer getWeight() {
		return this.weight;}

	public void setWeight(Integer weight) {
		this.weight = weight;}

	public String getPosition() {
		return this.position;}

	public void setPosition(String position) {
		this.position = position;}

	public Integer getSalary() {
		return this.salary;}

	public void setSalary(Integer salary) {
		this.salary = salary;}

	public Set<Stats> getStats() {
		return this.stats;}

	public void setStatses(Set<Stats> stats) {
		this.stats = stats;}

}
